### PR TITLE
Feature: Haptics and Sensitivity

### LINKED ISSUE #15: Virtual detents
Do we know if the dial supports virtual detents? This would be a very cool feature to add, for feedback.

I also thought I read somewhere that it supports vibration feedback.

### PR DESCRIPTION
**Pull request by jerrywoohu**
# Description

Enabled haptics by sending an HID message to the dial. This feature also introduces a change to how sensitivity works. Previously sensitivity increased or decreased the number of lines scrolled or amount of volume change, but did not truly change how sensitive the dial was. Now it works like changing the DPI setting on a mouse; it increases the amount of events generated per angle physically rotated. This way the haptics match the sensitivity.

Some changes may be necessary to retune the `multiplier` value in `ScrollController`.

Fixes #15 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Launching mac-dial restores previous settings. Quitting mac-dial turns off haptics and restores the default sensitivity. Changing sensitivity and enabling/disabling haptics works as expected. Project generates no new errors and uses general architecture of original project to achieve the feature.

### CODE REVIEW

**Comment by disarmyouwitha** [comment]
This is awesome, thank you so much!

I really like how it sounds and feels, and how sensitivity works now is very cool as well~

**Comment by bernhard-adobe** [comment]
this is pretty cool @jerrywoohu!
I was able to build the app and get the haptic feedback and the logs are showing. 
Screen Shot 2022-10-19 at 23 56 05


I am however not able to change the volume or scroll. Am I missing a module that needs to be installed or some permissions?
Or maybe would you be able to provide a release? Thanks for this cool contribution!

**Comment by mglobetx** [comment]
Changing the true sensitivity of the Dial is a big improvement.  Looking forward to trying it out once released.  Sorry I'm not a coder, so can only comment on functionality and serve as a tester.

This is probably way down the road, but there's I think a lot of folks that would like to be able to output ir codes from the host computer to be able to control volume on their audio gear.  For me for example, I'd like to be able to control a miniDSP flex, which can't hear BT, but can hear and react to conventional ir remotes.

**Comment by JMHAVANCE** [comment]
> this is pretty cool @jerrywoohu! I was able to build the app and get the haptic feedback and the logs are showing. Screen Shot 2022-10-19 at 23 56 05
> 
> I am however not able to change the volume or scroll. Am I missing a module that needs to be installed or some permissions? Or maybe would you be able to provide a release? Thanks for this cool contribution!

**It's probably this:**
https://github.com/andreasjhkarlsson/mac-dial/issues/12

When I was testing I needed to fully remove/re-add MacDial to the Accessibility settings to get it to work again between builds.

As an aside, I would probably change the Scroll Sensitivity to "High" at max, I think Extreme was an experimental option, as it cranks the dial up to 360

**Comment by bernhard-adobe** [comment]
@JMHAVANCE that was exactly it. #12 described part of it. 
The following steps have to be taken:
1. Replace the MacDial.app with the new built version. Meaning either deleting the old app or over-writing it with the new built.
2. Go to Accessibility and remove and add again MacDial or just remove it and then grant accessibility when interacting with the dial as the Accessibility request popup should appear.
However, it's in any case important to remove / replace the previous app with the new one. Starting the app from a built folder will not work.
Screen-Shot-2022-10-20-at-11 48 27

**Comment by bernhard-adobe** [comment]
@jerrywoohu other great feature ideas could be:
- adding the option for arrow keys left / right to be triggered when turning the dial (great for video scrubbing etc. )
- adding the option for custom keys or keys `[` and `]`  as those are the default brush size keys for Photoshop :)

Really good stuff!

**Comment by jerrywoohu** [comment]
> @jerrywoohu other great feature ideas could be:
> 
>     * adding the option for arrow keys left / right to be triggered when turning the dial (great for video scrubbing etc. )
> 
>     * adding the option for custom keys or keys `[` and `]`  as those are the default brush size keys for Photoshop :)
> 
> 
> Really good stuff!

@bernhard-adobe 

I went on to further customize the build with a toggle-able mode for zooming and horizontal scrolling in Final Cut. You'd press the Dial to toggle between zooming and scrolling (zooming had haptics and scrolling did not). I implemented zoom with keyboard events (CMD+/CMD-), but it wasn't smooth. I was exploring ways to hook into Apple's smooth pinch-to-zoom technique by emulating trackpad events, and I looked at other projects that had smooth zooming implemented, but couldn't tease apart how it was done.

Though it didn't end up being practical because the dial kept going to sleep while I was editing and it would take a few seconds to reconnect after waking—making it very frustrating to use in practice. I'd sit there and spin the dial for a few seconds before it started responding in Final Cut. 

This could be solved by either improving the reconnect time, or increasing the idle timeout at the expense of power consumption.

**Comment by bernhard-adobe** [comment]
hmm @jerrywoohu , after the device sleep the haptic feedback seems to be disabled and the speed is set to medium.
Clicking again in the menu on the correct speed or the haptic feedback option enables it again.

I checked the config file under `/Users/bschmidt/Library/Preferences/com.andreasjhkarlsson.MacDial.plist`and the haptic feedback settings are there but they seem to be not read on wake-up. Any suggestions how to fix this? 

````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>hapticsmode</key>
	<string>enabled</string>
	<key>mode</key>
	<string>playback</string>
	<key>sensitivity</key>
	<string>extreme</string>
</dict>
</plist>

````
Thanks for taking a look into this!

**Comment by bernhard-adobe** [comment]
Figured it out. Adding `device.updateSensitivity()` to https://github.com/jerrywoohu/mac-dial/blob/feature-haptics/MacDial/Dial.swift#L279 fixes the problem. Sets haptics and sensitivity after re-connect due to sleep time-out

**Comment by JMHAVANCE** [comment]
> Figured it out. Adding `device.updateSensitivity()` to https://github.com/jerrywoohu/mac-dial/blob/feature-haptics/MacDial/Dial.swift#L279 fixes the problem. Sets haptics and sensitivity after re-connect due to sleep time-out

Thanks for this. =] This has been bugging me because I love the haptics but it gets turned off every time it goes to sleep. ^^;

**Comment by jerrywoohu** [comment]
> Figured it out. Adding `device.updateSensitivity()` to https://github.com/jerrywoohu/mac-dial/blob/feature-haptics/MacDial/Dial.swift#L279 fixes the problem. Sets haptics and sensitivity after re-connect due to sleep time-out

Thanks! I've added this fix to this branch.

**Comment by andreasjhkarlsson** [comment]
Sorry for the slow feedback, I'm not active on github so I tend to miss stuff like this.

Really cool feature, did not know that the dial supported this. Will do some testing and then merge later (thanks for a tidy PR).

Will also see if I can anything about #12 and do a new release.

**Review by andreasjhkarlsson — APPROVED** [review]

**Pull request merged**
